#!/usr/bin/env python3

import socket
import sys

sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
addr = input('Enter your IP-address: ')

try:
    sock.connect((addr, 1303))
except OSError:
    print('Address alreay in use')
    sys.exit(0)

data = sock.recv(1024)

print(data.decode())

sock.close()