#!/usr/bin/env python3

import sys
import socket
from datetime import datetime

sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock.bind('0.0.0.0', 1303)
sock.listen()

try:
    while True:
        conn, addr = sock.accept()
        data = datetime.now().strftime("%d.%m.%Y %H:%M").encode()
        conn.send(data)
        conn.close()
        
except KeyboardInterrupt:
    sys.exit(0)